ELS Code/main/default/objects/Campaign/fields/Total_Conversions__c.field-meta.xml
<CustomField>
    <fullName>Total_Conversions__c</fullName>
    <label>Total Conversions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ELS Code/main/default/objects/Campaign_Reservation_Junction__c/Campaign_Reservation_Junction__c.object-meta.xml
<CustomObject>
    <label>Campaign Reservation Junction</label>
    <nameField>
        <label>Campaign Reservation Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Reservation Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ELS Code/main/default/objects/Campaign_Reservation_Junction__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Reservation Junctions</relationshipLabel>
    <relationshipName>Campaign_Reservation_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ELS Code/main/default/objects/Campaign_Reservation_Junction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Reservation Junctions</relationshipLabel>
    <relationshipName>Campaign_Reservation_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

ELS Code/main/default/objects/Campaign_Reservation_Junction__c/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Promo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Contact</label>
</CustomObject>

ELS Code/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/classes/CampResJuncTriggerHandler.cls
public with sharing class CampResJuncTriggerHandler {
    public static void afterInsert(Map<Id,Campaign_Reservation_Junction__c> newMap){
        List<Id> campaignIds = new List<Id>();
        for(Campaign_Reservation_Junction__c junc : newMap.values()){
            campaignIds.add(junc.Campaign__c);
        }

        Map<Id,Campaign> campaignMap = new Map<Id,Campaign>([SELECT Total_Conversions__c, Id FROM Campaign WHERE Id IN :campaignIds]);
        updateCampaign(campaignMap);
    }
    public static void afterDelete(Map<Id,Campaign_Reservation_Junction__c> oldMap){
        List<Id> campaignIds = new List<Id>();
        for(Campaign_Reservation_Junction__c junc : oldMap.values()){
            campaignIds.add(junc.Campaign__c);
        }

        Map<Id,Campaign> campaignMap = new Map<Id,Campaign>([SELECT Total_Conversions__c, Id FROM Campaign WHERE Id IN :campaignIds]);
        updateCampaign(campaignMap);
    }

    public static void updateCampaign(Map<Id,Campaign> campaignMap){
        AggregateResult[] arList = [SELECT COUNT_DISTINCT(Contact__c)amount, Campaign__c FROM Campaign_Reservation_Junction__c WHERE Campaign__c IN :campaignMap.keySet() AND Revenue_Type__c != 'Promo' GROUP BY Campaign__c];
        List<Campaign> campToUpdate = new List<Campaign>();
        Set<Id> campaignIds = new Set<Id>();

        for(AggregateResult ar : arList){
            System.debug(ar.get('amount'));
            campaignMap.get((Id)ar.get('Campaign__c')).Total_Conversions__c = (Decimal)ar.get('amount');
            campToUpdate.add(campaignMap.get((Id)ar.get('Campaign__c')));
            campaignIds.add((Id)ar.get('Campaign__c'));
        }

        for(Id cId : campaignMap.keySet()){
            if(!campaignIds.contains(cId)){
                campaignMap.get(cId).Total_Conversions__c = 0;
                campToUpdate.add(campaignMap.get(cId));
            }
        }
        System.debug(campToUpdate);

        update campToUpdate;
    }
}