ELS Code/main/default/objects/Contact/fields/Add_Date__c.field-meta.xml
<CustomField>
    <fullName>Add_Date__c</fullName>
    <label>Add Date</label>
    <type>Date</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Originating_Source__c.field-meta.xml
<CustomField>
    <fullName>Originating_Source__c</fullName>
    <label>Originating Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Co-registration</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Discount Camping</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paid Online</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ready Camp Go</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Voyager RV</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>KOA Leads</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Tradeshow</fullName>
            </value>
            <value>
                <fullName>LazyDay Travel Center</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Tiny House</fullName>
            </value>
            <value>
                <fullName>Petite Retreats</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Digital Display Booking</fullName>
            </value>
            <value>
                <fullName>RV Dealer Partners</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_Add_Date__c.field-meta.xml
<CustomField>
    <fullName>Source_Add_Date__c</fullName>
    <label>Source Add Date</label>
    <type>Date</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Source_Description__c</fullName>
    <description>Used to store description of Sources.</description>
    <label>Source Description</label>
    <type>TextArea</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_ID_2__c.field-meta.xml
<CustomField>
    <fullName>Source_ID_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source ID</label>
    <referenceTo>Sources__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <description>Used to save source id.</description>
    <label>Originating Source ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Sources__c/Sources__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store sources of contact.</description>
    <label>Sources</label>
    <nameField>
        <displayFormat>SRC-{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ELS Code/main/default/objects/Sources__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <description>This field will be used as external ID for sources.</description>
    <externalId>true</externalId>
    <label>Source ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ELS Code/main/default/objects/Sources__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Discount Camping</fullName>
            </value>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Paid Online</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ready Camp Go</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Trial Camping</fullName>
            </value>
            <value>
                <fullName>TradeShow</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>Voyager RV</fullName>
            </value>
            <value>
                <fullName>KOA Leads</fullName>
            </value>
            <value>
                <fullName>Co-registration</fullName>
            </value>
            <value>
                <fullName>LazyDay Travel Center</fullName>
            </value>
            <value>
                <fullName>Digital Display Booking</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Petite Retreats</fullName>
            </value>
            <value>
                <fullName>Tiny House</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>RV Dealer Submission</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CampUSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Sources__c/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Contact Inquiry</fullName>
            </value>
            <value>
                <fullName>Directory Request - Hard copy</fullName>
            </value>
            <value>
                <fullName>Directory Request - Soft Copy</fullName>
            </value>
            <value>
                <fullName>Event RSVP</fullName>
            </value>
            <value>
                <fullName>General Info</fullName>
            </value>
            <value>
                <fullName>Media Inquiry</fullName>
            </value>
            <value>
                <fullName>Newsletter</fullName>
            </value>
            <value>
                <fullName>Promotional</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Sweepstakes</fullName>
            </value>
            <value>
                <fullName>Tradeshow/Rally</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Bing</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Pandora</fullName>
            </value>
            <value>
                <fullName>Yahoo</fullName>
            </value>
            <value>
                <fullName>Atlantic City</fullName>
            </value>
            <value>
                <fullName>Blue Crick RV &amp; Truck</fullName>
            </value>
            <value>
                <fullName>Boat N RV Superstore</fullName>
            </value>
            <value>
                <fullName>Boston RV</fullName>
            </value>
            <value>
                <fullName>Central Valley Sportsmens Show</fullName>
            </value>
            <value>
                <fullName>Charlotte RV</fullName>
            </value>
            <value>
                <fullName>Dallas Summer boat show</fullName>
            </value>
            <value>
                <fullName>Greensboro RV</fullName>
            </value>
            <value>
                <fullName>Harrisburg</fullName>
            </value>
            <value>
                <fullName>Holiday World</fullName>
            </value>
            <value>
                <fullName>La Mesa RV Cebter</fullName>
            </value>
            <value>
                <fullName>Quartzsite RV</fullName>
            </value>
            <value>
                <fullName>Raleigh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/classes/SourceUtil.cls
/*
Name        : SourceUtil 
Author      : Mahwish Iqbal
Date        : 6-June-2015
Version     : 1.0
Description : This class contain functions related to source object
        
*/
public without sharing class SourceUtil {  
  
    list<Sources__c> lstOfSources;
    
    public map<string, Sources__c> mapOfSource;
    public map<string, Contact> mapOfContact;

        
    public SourceUtil(){
       
        lstOfSources = new List<Sources__c>();    // Initializing List
        mapOfSource = new map<string, Sources__c>();
        mapOfContact = new map<string, Contact>();  
    }
    
    
    public void getSourceList(List<Sources__c> pLstSrc){
    
        this.lstOfSources = pLstSrc;            // Set list of source records
        decimal iCounter = getSourceCounter();  // Get current max count
        setSourceCounter(iCounter);            // set count value to update Source Id        
    }
    
    
    decimal getSourceCounter(){
    
     decimal iCounter;
        
        /*Select max count*/ 
        for(AggregateResult ar : [select Max(Counter__c) counter from Sources__c]){     
           iCounter = (decimal) ar.get('counter');
        }  
    return iCounter;
    }

    public void setSourceCounter(decimal pCounter){
    
        if(pCounter == null) pCounter = 0;
        /*iterate over list of Source to set auto generated value to Source Id*/ 
        if(lstOfSources.size() > 0){
            for(Sources__c src :  lstOfSources){
                
                if(src.Source_ID__c == null) {          
                    pCounter ++;           
                   // src.Source_ID__c = 'SRC-'+FormatNumber(pCounter);          
                    src.Counter__c = pCounter ;   
                }
            }
        }  
    }
    
    
     public void getSourcesById(Set<string> pSetOfSourceID ){
		System.debug('Enter SourceUtil getContactSources');
       for(Sources__c src : [Select ID, Source_ID__c, Source_Type__c, Description__c from Sources__c where Source_ID__c in : pSetOfSourceID]){      
            mapOfSource.put(src.Source_ID__c.toLowerCase(), src);
           System.debug('mapOfSource'+mapOfSource.values());
        }
    }
    
    
    public void getContactSources(Set<string> pSetOfContactID){
		System.debug('Enter SourceUtil getContactSources');
      for(Contact con : [Select ID, Source_Description__c, Source_Add_Date__c,Add_Date__c,  Source_ID__c, Source_ID_2__c, Originating_Source__c from Contact where ID in : pSetOfContactID]){   
            mapOfContact.put(con.ID, con); 
          System.debug('mapOfContact'+mapOfContact.values());
        }
    }
    
    public map<string, Sources__c> getSources(){
    
       map<string, Sources__c>  mapOfAllSources = new map<string, Sources__c>();
         
       for(Sources__c src : [Select ID, Source_ID__c, Source_Type__c,Sub_Type__c, Description__c from Sources__c]){     
            if(!String.IsBlank(src.Source_ID__c))
                mapOfAllSources.put(src.Source_ID__c.toLowerCase(), src); 
        }
        
        return mapOfAllSources;
    }
    
     public map<string, Sources__c> getLowerCaseSources(){ 
    
       map<string, Sources__c>  mapOfAllSources = new map<string, Sources__c>();
         
       for(Sources__c src : [Select ID, Source_ID__c, Source_Type__c,Sub_Type__c, Description__c from Sources__c]){     
            if(!String.IsBlank(src.Source_ID__c))
                mapOfAllSources.put(src.Source_ID__c.toLowerCase(), src); 
        }
        
        return mapOfAllSources;
    }
   
}