ELS Code/main/default/objects/Contact/fields/Add_Date__c.field-meta.xml
<CustomField>
    <fullName>Add_Date__c</fullName>
    <label>Add Date</label>
    <type>Date</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Originating_Source__c.field-meta.xml
<CustomField>
    <fullName>Originating_Source__c</fullName>
    <label>Originating Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Co-registration</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Discount Camping</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paid Online</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ready Camp Go</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Voyager RV</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>KOA Leads</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Tradeshow</fullName>
            </value>
            <value>
                <fullName>LazyDay Travel Center</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Tiny House</fullName>
            </value>
            <value>
                <fullName>Petite Retreats</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Digital Display Booking</fullName>
            </value>
            <value>
                <fullName>RV Dealer Partners</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Source_Description__c</fullName>
    <description>Used to store description of Sources.</description>
    <label>Source Description</label>
    <type>TextArea</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_ID_2__c.field-meta.xml
<CustomField>
    <fullName>Source_ID_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source ID</label>
    <referenceTo>Sources__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <description>Used to save source id.</description>
    <label>Originating Source ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/Contact_Sources__c.object-meta.xml
<CustomObject>
    <description>Junction object between Contact and Sources objects.</description>
    <label>Activities and Interests</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities and Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ELS Code/main/default/objects/Contact_Sources__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Sources_ID__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <formula>Sources_ID__r.Source_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source ID</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <formula>Text (Sources_ID__r.Source_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Type</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/Sources_ID__c.field-meta.xml
<CustomField>
    <fullName>Sources_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source ID</label>
    <referenceTo>Sources__c</referenceTo>
    <relationshipName>Contact_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/What_experience_would_you_like_to_win__c.field-meta.xml
<CustomField>
    <fullName>What_experience_would_you_like_to_win__c</fullName>
    <label>What experience would you like to win?</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/What_s_your_Ideal_Getaway__c.field-meta.xml
<CustomField>
    <fullName>What_s_your_Ideal_Getaway__c</fullName>
    <label>What&apos;s your Ideal Getaway?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ELS Code/main/default/objects/Contact_Sources__c/fields/Where_are_you_Interested_in_Camping__c.field-meta.xml
<CustomField>
    <fullName>Where_are_you_Interested_in_Camping__c</fullName>
    <label>Where are you Interested in Camping?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ELS Code/main/default/objects/Sources__c/Sources__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store sources of contact.</description>
    <label>Sources</label>
    <nameField>
        <displayFormat>SRC-{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ELS Code/main/default/objects/Sources__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <description>This field will be used as external ID for sources.</description>
    <externalId>true</externalId>
    <label>Source ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ELS Code/main/default/objects/Sources__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Discount Camping</fullName>
            </value>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Paid Online</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Ready Camp Go</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Trial Camping</fullName>
            </value>
            <value>
                <fullName>TradeShow</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>Voyager RV</fullName>
            </value>
            <value>
                <fullName>KOA Leads</fullName>
            </value>
            <value>
                <fullName>Co-registration</fullName>
            </value>
            <value>
                <fullName>LazyDay Travel Center</fullName>
            </value>
            <value>
                <fullName>Digital Display Booking</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Petite Retreats</fullName>
            </value>
            <value>
                <fullName>Tiny House</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>RV Dealer Submission</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CampUSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/Zapier_logs__c.object-meta.xml
<CustomObject>
    <label>Zapier log</label>
    <nameField>
        <displayFormat>log - {00000}</displayFormat>
        <label>Zapier logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zapier logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ELS Code/main/default/objects/Zapier_logs__c/fields/ContactId_Error__c.field-meta.xml
<CustomField>
    <fullName>ContactId_Error__c</fullName>
    <label>ContactId/Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <label>Source ID</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/State_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence__c</fullName>
    <label>State of Residence</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/What_experience_would_you_like_to_win__c.field-meta.xml
<CustomField>
    <fullName>What_experience_would_you_like_to_win__c</fullName>
    <label>What experience would you like to win?</label>
    <type>TextArea</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/What_s_your_Ideal_Getaway__c.field-meta.xml
<CustomField>
    <fullName>What_s_your_Ideal_Getaway__c</fullName>
    <label>What&apos;s your Ideal Getaway?</label>
    <type>TextArea</type>
</CustomField>

ELS Code/main/default/objects/Zapier_logs__c/fields/Where_are_you_Interested_in_Camping__c.field-meta.xml
<CustomField>
    <fullName>Where_are_you_Interested_in_Camping__c</fullName>
    <label>Where are you Interested in Camping?</label>
    <type>TextArea</type>
</CustomField>

ELS Code/main/default/classes/ZapierLogTriggerHandler.cls
public class ZapierLogTriggerHandler {
    
    public static void handleAfterInsert(Map<Id,Zapier_logs__c> newMap) {
        createContact(newMap);    
    }
    
    public static void createContact(Map<Id,Zapier_logs__c> newMap){
        Map<string, Sources__c> imapOfSources = new map<string, Sources__c>();
        SourceUtil objSource = new SourceUtil();
        List<Contact_Sources__c> ListOfActInterest = new List<Contact_Sources__c>();
        Map<Id,Zapier_logs__c> mapContactZapierLog = new Map<Id,Zapier_logs__c>();
        Map<Id,contact> newContactCreatedmap = new Map<Id,Contact>();
        system.debug('newMap.values()'+newMap); 
        for(Zapier_logs__c objZapLog : newMap.values()){
            
            Contact objCon = new Contact();
            if(objZapLog.first_Name__c!=null){
                objCon.FirstName = objZapLog.first_Name__c;
            }else{
                objCon.FirstName = 'Camper';
            }
            
            if(objZapLog.Last_name__c!=null){
                objCon.LastName = objZapLog.Last_name__c;
            }else{
                objCon.LastName = 'Lname';
            }
            
            if(objZapLog.Email__c!=null){
                objCon.Email = objZapLog.Email__c;
            }else{
                objCon.Email = 'noemail@noemail.com';
            }
            
            if(objZapLog.State_of_Residence__c!=null && objZapLog.Country__c!=null){
                objCon.MailingState = objZapLog.State_of_Residence__c;
                objCon.MailingCountry = objZapLog.Country__c;
                objCon.MailingCity = 'Anytown';
                objCon.MailingPostalCode = '99999';
                objCon.MailingStreet = '123 Main St';
            }
            imapOfSources = objSource.getLowerCaseSources();
            if (objZapLog!=null && !String.IsBlank(objZapLog.Source_ID__c) && imapOfSources.containsKey(objZapLog.Source_ID__c.toLowerCase())) {
                objCon.Originating_Source__c = imapOfSources.get(objZapLog.Source_ID__c.toLowerCase()).Source_Type__c;
                objCon.Source_ID__c = imapOfSources.get(objZapLog.Source_ID__c.toLowerCase()).Source_ID__c;
                objCon.Source_ID_2__c = imapOfSources.get(objZapLog.Source_ID__c.toLowerCase()).id;
                objCon.Source_Description__c = imapOfSources.get(objZapLog.Source_ID__c.toLowerCase()).Description__c;
            }else{
                objCon.Originating_Source__c = 'Zapier';
            }
            newContactCreatedmap.put(objZapLog.Id,objCon);
        }
        if(newContactCreatedmap.size()>0){
            try{
                insert newContactCreatedmap.values();
                list<Zapier_logs__c> zapLoglist = new list<Zapier_logs__c>();
                for(Zapier_logs__c objZapLog : newMap.values()){
                    zapLoglist.add(new Zapier_logs__c(id=objZapLog.id,ContactId_Error__c = newContactCreatedmap.get(objZapLog.id).Id) ); 
                    mapContactZapierLog.put(newContactCreatedmap.get(objZapLog.id).Id,objZapLog);
                }
                if(zapLoglist.size()>0){
                    update zapLoglist;
                }
                imapOfSources = objSource.getLowerCaseSources();
                for(Contact objCon : newContactCreatedmap.values()){
                    Zapier_logs__c objZapLog = (mapContactZapierLog.containsKey(objCon.id)) ? mapContactZapierLog.get(objCon.id) : null;
                    Contact_Sources__c ActInterest = new Contact_Sources__c();
                    ActInterest.Contact_Id__c = objCon.Id;
                    if(objZapLog.What_experience_would_you_like_to_win__c!=null){
                        ActInterest.What_experience_would_you_like_to_win__c=objZapLog.What_experience_would_you_like_to_win__c;    
                    }
                    if(objZapLog.What_s_your_Ideal_Getaway__c!=null){
                        ActInterest.What_s_your_Ideal_Getaway__c = objZapLog.What_s_your_Ideal_Getaway__c;   
                    }
                    if(objZapLog.Where_are_you_Interested_in_Camping__c!=null){
                        ActInterest.Where_are_you_Interested_in_Camping__c = objZapLog.Where_are_you_Interested_in_Camping__c;   
                    }
                    if (objZapLog!=null && !String.IsBlank(objZapLog.Source_ID__c) && imapOfSources.containsKey(objZapLog.Source_ID__c.toLowerCase())) {
                        ActInterest.Sources_ID__c = imapOfSources.get(objZapLog.Source_ID__c.toLowerCase()).Id;
                        ActInterest.Source_Description__c  = imapOfSources.get(objZapLog.Source_ID__c.toLowerCase()).Description__c;
                    }
                    ActInterest.Add_Date__c = system.today();
                    ListOfActInterest.add(ActInterest);
                }
                if (ListOfActInterest.size()  > 0 ){
                    insert ListOfActInterest;
                }
            }Catch(exception ex){
                for(Zapier_logs__c objZapLog : newMap.values()){
                    objZapLog.ContactId_Error__c = ex.getStackTraceString()+ex.getMessage();
                }
            }          
        }
        system.debug(newContactCreatedmap.values());        
    }
}