ELS Code/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ELS Code/main/default/objects/Log__c/fields/No_Of_Error_Records__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Error_Records__c</fullName>
    <label>No. Of Error Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ELS Code/main/default/objects/Log__c/fields/No_Of_Inserted_Records__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Inserted_Records__c</fullName>
    <label>No. Of Inserted Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ELS Code/main/default/objects/Log__c/fields/No_Of_Processed_Records__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Processed_Records__c</fullName>
    <label>No. Of Processed Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ELS Code/main/default/objects/Log__c/fields/No_Of_Updated_Records__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Updated_Records__c</fullName>
    <label>No. Of Updated Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ELS Code/main/default/classes/LogsUtil.cls
/*
Class       : LogsUtil 
Author      : Mahwish Iqbal
Date        : 18-Dec-2013
Version     : 1.0
Description : 
*/
public without sharing class LogsUtil {  
    
    
    public string logDesc;
    public integer Inserted;
    public integer Updated;
    public integer errors;
    public integer success;
    public string source;
    
    /*******************************CONSTRUCTOR******************/
    public LogsUtil (){
          
        
     //   obj = new DedupUtil2(iObject );
      //  iListWrapperDedup = new List<WrapperDedup>(); 
      
    
    }//End of Constructor
    
   
    public void CreateLogs(){
        
        Log__c l = new Log__c();
        l.Error_Description__c = logDesc;
        l.No_Of_Error_Records__c = errors;
        l.No_Of_Inserted_Records__c = Inserted;
        l.No_Of_Processed_Records__c = success;
        l.No_Of_Updated_Records__c = updated;
        l.source__c = source;
        insert l;
    }
    
}