ELS Code/main/default/objects/ClientID__c/ClientID__c.object-meta.xml
<CustomObject>
    <label>ClientID</label>
    <nameField>
        <label>Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClientID</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ELS Code/main/default/objects/ClientID__c/fields/CAMPUSAPROFILE__c.field-meta.xml
<CustomField>
    <fullName>CAMPUSAPROFILE__c</fullName>
    <label>CAMPUSAPROFILE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>AOR</fullName>
            </value>
            <value>
                <fullName>Coast to Coast</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Encore</fullName>
            </value>
            <value>
                <fullName>Guest of Manager</fullName>
            </value>
            <value>
                <fullName>Guest of Members</fullName>
            </value>
            <value>
                <fullName>Guest of Sales</fullName>
            </value>
            <value>
                <fullName>Lazy Days Temp</fullName>
            </value>
            <value>
                <fullName>Marketing Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>ODW-Non Member</fullName>
            </value>
            <value>
                <fullName>Park Member</fullName>
            </value>
            <value>
                <fullName>Public Program</fullName>
            </value>
            <value>
                <fullName>R.P.I</fullName>
            </value>
            <value>
                <fullName>R.P.I. - Preferred</fullName>
            </value>
            <value>
                <fullName>Reciprocal System-other</fullName>
            </value>
            <value>
                <fullName>Reserve America</fullName>
            </value>
            <value>
                <fullName>Resorts of Destinction (ROD)</fullName>
            </value>
            <value>
                <fullName>ROD - Plus</fullName>
            </value>
            <value>
                <fullName>Sales Opportunity</fullName>
            </value>
            <value>
                <fullName>Super Host Attendee, Retail</fullName>
            </value>
            <value>
                <fullName>Walden Woods Member</fullName>
            </value>
            <value>
                <fullName>Whole Saler</fullName>
            </value>
            <value>
                <fullName>WHR Member</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/ClientID_External_ID__c.field-meta.xml
<CustomField>
    <fullName>ClientID_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>ClientID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ClientID</relationshipLabel>
    <relationshipName>ClientID</relationshipName>
    <type>Lookup</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/FLAS__c.field-meta.xml
<CustomField>
    <fullName>FLAS__c</fullName>
    <formula>IF( OR( ISBLANK( FirstName__c), ISBLANK( LastName__c), ISBLANK(Address_1__c+Address_2__c), ISBLANK( MailingState__c)) ,null,

IF ( AND( NOT(ISBLANK(Address_1__c)), NOT(ISBLANK(Address_2__c))), 
         MID( FirstName__c , 0, 1) &amp; LastName__c &amp; MID( Address_1__c+&apos; &apos;+Address_2__c , 0, 9) &amp; MailingState__c, 
          IF ( AND( NOT(ISBLANK(Address_1__c)), ISBLANK(Address_2__c)), 
                MID( FirstName__c , 0, 1) &amp; LastName__c &amp; MID( Address_1__c , 0, 9) &amp; MailingState__c, 
          IF ( AND( ISBLANK(Address_1__c), NOT(ISBLANK(Address_2__c))), 
               MID( FirstName__c , 0, 1) &amp; LastName__c &amp; MID( Address_2__c , 0, 9) &amp; MailingState__c, IF ( AND( ISBLANK(Address_1__c), ISBLANK(Address_2__c) ), 
               MID( FirstName__c , 0, 1) &amp; LastName__c &amp; MailingState__c, &apos;&apos;
         )
      )
   )
)

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FLAS</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/LAZ__c.field-meta.xml
<CustomField>
    <fullName>LAZ__c</fullName>
    <formula>IF( OR(  ISBLANK( LastName__c), ISBLANK(Address_1__c+Address_2__c), ISBLANK( MailingPostalCode__c)) ,null, 

IF ( AND( NOT(ISBLANK(Address_1__c)), NOT(ISBLANK(Address_2__c))), 
         LastName__c &amp; MID( Address_1__c+&apos; &apos;+Address_2__c , 0, 9) &amp; MID( MailingPostalCode__c , 0, 5), 
          IF ( AND( NOT(ISBLANK(Address_1__c)), ISBLANK(Address_2__c)), 
                LastName__c &amp; MID( Address_1__c, 0, 9) &amp; MID( MailingPostalCode__c , 0, 5), 

          IF ( AND( ISBLANK(Address_1__c), NOT(ISBLANK(Address_2__c))), 
              LastName__c &amp; MID(Address_2__c , 0, 9) &amp; MID( MailingPostalCode__c , 0, 5), IF ( AND( ISBLANK(Address_1__c), ISBLANK(Address_2__c) ), 
              LastName__c &amp; MID( MailingPostalCode__c , 0, 5), &apos;&apos;
         )
      )
   )
)

)</formula>
    <label>LAZ</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/MailingCity__c.field-meta.xml
<CustomField>
    <fullName>MailingCity__c</fullName>
    <label>MailingCity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/MailingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>MailingPostalCode__c</fullName>
    <label>MailingPostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/MailingState__c.field-meta.xml
<CustomField>
    <fullName>MailingState__c</fullName>
    <label>MailingState</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/PF__c.field-meta.xml
<CustomField>
    <fullName>PF__c</fullName>
    <formula>IF( OR( ISBLANK( Phone__c ), ISBLANK( FirstName__c)) ,null, Phone__c &amp; FirstName__c)</formula>
    <label>PF</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/PL__c.field-meta.xml
<CustomField>
    <fullName>PL__c</fullName>
    <formula>IF( OR( ISBLANK( Phone__c ), ISBLANK( LastName__c )) ,null, Phone__c &amp; LastName__c)</formula>
    <label>PL</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/ClientID__c/fields/RVOT__c.field-meta.xml
<CustomField>
    <fullName>RVOT__c</fullName>
    <label>RVOTGPROFILE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Contact/fields/CAMPUSAPROFILE__c.field-meta.xml
<CustomField>
    <fullName>CAMPUSAPROFILE__c</fullName>
    <label>CAMPUSAPROFILE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Contact/fields/DG_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>DG_Contact_Type__c</fullName>
    <label>DG_Contact_Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ELS Code/main/default/objects/Contact/fields/FLAS_2__c.field-meta.xml
<CustomField>
    <fullName>FLAS_2__c</fullName>
    <formula>IF( OR( ISBLANK(OtherStreet) , ISBLANK(OtherState) , ISBLANK(FirstName ), ISBLANK(LastName),  Is_Default_First_Name__c, Is_Default_Last_Name__c,  Is_Default_Other_Address__c ) , null, MID( FirstName , 0, 1) &amp; MID(LastName,0,3)&amp;  OtherStreet &amp;  OtherState)</formula>
    <label>FLAS 2</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/FLAS__c.field-meta.xml
<CustomField>
    <fullName>FLAS__c</fullName>
    <formula>IF( OR( ISBLANK(FirstName ) , ISBLANK(LastName ) , ISBLANK(MailingStreet ),  ISBLANK(MailingState),  Is_Default_First_Name__c,  Is_Default_Last_Name__c , Is_Default_Address__c) , null, MID( FirstName , 0, 1) &amp; MID( LastName ,0, 3) &amp;  MailingStreet  &amp;  MailingState)</formula>
    <label>FLAS</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/LAZ_2__c.field-meta.xml
<CustomField>
    <fullName>LAZ_2__c</fullName>
    <formula>IF(OR(ISBLANK(FirstName),ISBLANK(LastName),ISBLANK(OtherPostalCode) , ISBLANK(OtherStreet),  Is_Default_Last_Name__c,  Is_Default_Other_Address__c ) , null,MID(FirstName,0,1) &amp; MID(LastName, 0,3) &amp; OtherStreet &amp; MID(OtherPostalCode , 0, 5))</formula>
    <label>LAZ 2</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/LAZ__c.field-meta.xml
<CustomField>
    <fullName>LAZ__c</fullName>
    <formula>IF( IS_MAILING_HOUSE__c ,(LastName &amp;( MailingStreet) &amp; MID( MailingPostalCode , 0, 5)), (IF(OR(ISBLANK(MailingStreet ), ISBLANK(MailingPostalCode ), Is_Default_Address__c, Is_Default_Last_Name__c ) , null, LastName &amp; MID( MailingStreet , 0, 9) &amp; MID( MailingPostalCode , 0, 5))))</formula>
    <label>LAZ</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/PF_2__c.field-meta.xml
<CustomField>
    <fullName>PF_2__c</fullName>
    <formula>IF( OR( ISBLANK( OtherPhone  ) , ISBLANK( FirstName ),  Is_Default_First_Name__c, Is_Default_Other_Phone__c  ) , null, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(OtherPhone, &quot;+&quot;, &quot;&quot;), &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;), &quot; &quot;,&quot;&quot;), &quot;.&quot;,&quot;&quot;), &quot;/&quot;,&quot;&quot;)&amp; FirstName)</formula>
    <label>PF 2</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/PF__c.field-meta.xml
<CustomField>
    <fullName>PF__c</fullName>
    <description>Used to store PF value used in matching criteria for de-duplication of contacts.</description>
    <formula>IF( OR( ISBLANK( Phone ) , ISBLANK( FirstName ),  Is_Default_First_Name__c,  Is_Default_Phone__c  ) , null, SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE( SUBSTITUTE(SUBSTITUTE(Phone, &quot;+&quot;, &quot;&quot;), &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;), &quot; &quot;,&quot;&quot;), &quot;.&quot;,&quot;&quot;), &quot;/&quot;,&quot;&quot;) &amp;  FirstName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PF</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/PL_2__c.field-meta.xml
<CustomField>
    <fullName>PL_2__c</fullName>
    <formula>IF( OR( ISBLANK( OtherPhone), ISBLANK( LastName ),  Is_Default_Last_Name__c,  Is_Default_Other_Phone__c  ) ,null, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(OtherPhone, &quot;+&quot;, &quot;&quot;), &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;), &quot; &quot;,&quot;&quot;), &quot;.&quot;,&quot;&quot;), &quot;/&quot;,&quot;&quot;) &amp; LastName)</formula>
    <label>PL 2</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact/fields/PL__c.field-meta.xml
<CustomField>
    <fullName>PL__c</fullName>
    <description>Used to store PL value used in de-duplication script</description>
    <formula>IF(  OR( ISBLANK( Phone ),  ISBLANK( LastName ),  Is_Default_Last_Name__c,  Is_Default_Phone__c  ) ,null,  SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(Phone, &quot;+&quot;, &quot;&quot;), &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;), &quot; &quot;,&quot;&quot;), &quot;.&quot;,&quot;&quot;), &quot;/&quot;,&quot;&quot;) &amp;  LastName)</formula>
    <label>PL</label>
    <type>Text</type>
</CustomField>

ELS Code/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Contact</label>
</CustomObject>

ELS Code/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ELS Code/main/default/classes/ClientIDUtil.cls
/*
Class       : ClientIDUtil
Author      : Mahwish Iqbal, Umer Aziz
Date        : 18-June-2015
Version     : 1.0
Description : This class contains functions related to ClientID object.
*/
public without sharing class ClientIDUtil{  
    
    string iObject;   
    DeDupUtil obj;
    /*******************************MAPS***********************/
    map<string,ID> iMapEmailCon;
    map<string,ID> iMapFLASCon;
    map<string,ID> iMapLAZCon;
    map<string,ID> iMapPFCon;
    map<string,ID> iMapPLCon;
    
    Public map<String, ID> MapofMemberandClient;
    
    Public List<Contact> lstofContacttoUpdate;
    
    /*******************************LISTS***********************/
    list<WrapperDedup> iListWrapperDedup;
    list<ClientID__c> ListOfClientID;
    
    /*******************************SETS***********************/
    Public set<String> SetofClientId;
    
    /******************************************** CONSTRUCTORS ***********************************/
    // This constructor accepts string as paramter to pass value in dedupUtil class constructor.
    
    public ClientIDUtil(string pObject){
          
        iObject = pObject; // set paramter value
        obj = new DedupUtil(iObject); // Initialize dedupe class and pass object to its constructor
        
        /*Initializing wrapper lists*/
        iListWrapperDedup = new List<WrapperDedup>(); 
        
        /*Initializing maps*/
        iMapEmailCon = new map<string, ID>();
        iMapFLASCon = new map<string, ID>();
        iMapLAZCon = new map<string, ID>();
        iMapPFCon = new map<string, ID>();
        iMapPLCon = new map<string, ID>();
        
         /*Initializing lists*/
         ListOfClientID = new List<ClientID__c>();
    
    }//End of Constructor
    
    // This constructor accepts no paramter and has been called in membership trigger
    public ClientIDUtil(){
    
        MapofMemberandClient = new Map<String, ID>();
        SetofClientId = new set<String>();
        lstofContacttoUpdate = new List<Contact>();
    }
    

   /******************************************** GetContactID *****************************************/
   // This function is used to return map of Contact Id from Client Id records.
    Public void GetContactID(){
    
       List<ClientID__c> ListofClientID = [SELECT Contact__c, ClientID_External_ID__c, Id FROM ClientID__c where ClientID_External_ID__c IN:SetofClientId AND Contact__c!=null];
        
        if(ListofClientID.size()>0){
            for(ClientID__c cli : ListofClientID ){
                MapofMemberandClient.put(cli.ClientID_External_ID__c, cli.Contact__c);  
            
            } // End of for loop
            
            //Update Contact reference in membership
            for(Contact ConUpdate : [SELECT Id, DG_Contact_Type__c FROM Contact where ID IN : MapofMemberandClient.Values()]){
                ConUpdate.DG_Contact_Type__c = 'Customer';
                lstofContacttoUpdate.add(ConUpdate);
            }
            
            if(lstofContacttoUpdate.size()>0){
                upsert lstofContacttoUpdate;
            }//End of Update
        } // End of if 
    } // End of function
   
    /******************************************** GetClientID *****************************************/
    //This method is used to set values of wrapper type and add it in wrapper list from ClientID record
    public void GetClientID(List<ClientID__c> pListClientID){
        For(ClientID__c iClient : pListClientID){
            iListWrapperDedup.add(new WrapperDedup(iClient.Id, iClient.Email__c, iClient.FLAS__c, iClient.LAZ__c, iClient.PL__c, iClient.PF__c, iClient.FirstName__c, iClient.LastName__c, iClient.MailingCity__c, iClient.MailingPostalCode__c, iClient.MailingState__c, iClient.Address_1__c, iClient.Address_2__c, iClient.Phone__c, iClient.Contact__c, iClient.CAMPUSAPROFILE__c, iClient.Client_Type__c, iClient.RVOT__c, iClient.Create_Time__c, 'CLIENTID' ));
        } 
    }// End of function

    /******************************************** DedupClientID *****************************************/
    // This function is used to apply deduping on ClientID records and create/update contacts. 
    //After deduping process, it sets contact refrence to the ClientID record. 
    public void DedupClientID(){
    
        // Call dedupUtil class method to fill sets with all de duping criteria in wrapper list
        obj.MatchDeDupCriteria(iListWrapperDedup);
        
        // Call dedupUtil class method to apply deduping on records from wrapper list 
        obj.CheckDuplicates(iListWrapperDedup); 
        
        // Set contact lookup in ClientID  
        setContactLookup();
        
    }// End of function
   
    
    /******************************************** setContactLookup *********************************************/
    //This function is used to set Contact on ClientID record.
    public void setContactLookup(){
        
        // Itrate over wrapper list and set contact ids from existing contact maps from dedupe class
        for(WrapperDedup clid: iListWrapperDedup){
        
            if(clid.Email == null && clid.Flas == null && clid.LAZ == null && clid.PF == null && clid.PL == null){
            
                clid.ContactID = '003j000000alMxfAAE';
            
            }else{
        
	            //Check if contact exists with Email
	            if(obj.mapConAndEmail.ContainsKey(clid.Email)){
	                clid.ContactID = obj.mapConAndEmail.get(clid.Email).Id;
	            }
	            //Check if contact exists with FLAS
	            else if(obj.mapConAndFLAS.ContainsKey(clid.Flas)){
	                clid.ContactID = obj.mapConAndFLAS.get(clid.Flas).Id;
	            }
	            //Check if contact exists with LAZ
	            else if(obj.mapConAndLAZ.ContainsKey(clid.LAZ)){
	                clid.ContactID = obj.mapConAndLAZ.get(clid.LAZ).Id;
	            }
	            //Check if contact exists with PF
	            else if(obj.mapConAndPF.ContainsKey(clid.PF)){
	                clid.ContactID = obj.mapConAndPF.get(clid.PF).Id;
	            }
	            //Check if contact exists with PL
	            else if(obj.mapConAndPL.ContainsKey(clid.PL)){
	                clid.ContactID = obj.mapConAndPL.get(clid.PL).Id;
	            }
            }
        }

        List<Contact> lstOfContacts = getNewContacts();
            
        if(lstOfContacts.size() > 0){
            // Itration on map of insert contacts to create maps of Email, FLAS, LAZ, PL and PF
            for(Contact con : lstOfContacts){
            
                if(con.Email != null && !string.Isblank(con.Email))
                    iMapEmailCon.put(con.Email, con.id);
                    
                if(con.Email_2__c != null && !string.Isblank(con.Email_2__c))
                    iMapEmailCon.put(con.Email_2__c, con.id);
                    
                if(con.FLAS__c != null && !string.Isblank(con.FLAS__c))
                    iMapFLASCon.put(con.FLAS__c, con.id);
                
                if(con.FLAS_2__c != null && !string.Isblank(con.FLAS_2__c))
                    iMapFLASCon.put(con.FLAS_2__c, con.id);
                    
                if(con.LAZ__c != null && !string.Isblank(con.LAZ__c))
                    iMapLAZCon.put(con.LAZ__c, con.id);
                    
                if(con.LAZ_2__c != null && !string.Isblank(con.LAZ_2__c))
                    iMapLAZCon.put(con.LAZ_2__c, con.id);
                    
                if(con.PF__c != null && !string.Isblank(con.PF__c))
                    iMapPFCon.put(con.PF__c, con.id);
                
                if(con.PL__c != null && !string.Isblank(con.PL__c))
                    iMapPLCon.put(con.PL__c, con.id);
                        
            } // End of loop
    
            // Itrate over wrapper list and set contact ids from new inserted contact maps from dedupe class
            for(WrapperDedup clid: iListWrapperDedup){
            	
	            if(clid.Email == null && clid.Flas == null && clid.LAZ == null && clid.PF == null && clid.PL == null){
	            
	                 clid.ContactID = '003j000000alMxfAAE';
	            
	            }else{
                
	                if(iMapEmailCon.ContainsKey(clid.email)){
	                    clid.ContactID =  iMapEmailCon.get(clid.email);
	                }
	                else if(iMapFLASCon.ContainsKey(clid.FLAS )){
	                    clid.ContactID =  iMapFLASCon.get(clid.FLAS );
	                }
	                else if(iMapLAZCon.ContainsKey(clid.LAZ)){
	                    clid.ContactID =  iMapLAZCon.get(clid.LAZ);
	                }
	                else if(iMapPFCon.ContainsKey(clid.PF)){
	                    clid.ContactID =  iMapPFCon.get(clid.PF);
	                }
	                else if(iMapPLCon.ContainsKey(clid.PL))
	                    clid.ContactID =  iMapPLCon.get(clid.PL);
	            }
            } // End of loop
       }

        // Itrate over wrapper list and type cast wrapper values to ClientID 
        for(WrapperDedup iWrap : iListWrapperDedup){
            ClientID__c iClient = new ClientID__c();
            iClient.Contact__c = iWrap.contactID;         
            iClient.Id = iWrap.ID;
            
            ListOfClientID.add(iClient);
        }
        update ListOfClientID; //Update ClientID list
    } // End of function   
    
   
    /******************************************** getNewContacts *********************************************/
    //This function is used to get new contact from obj.mapOfContToInsert.values() map in dedup class
    public List<Contact> getNewContacts(){
    
        List<Contact> ListOfDupCon = new list <contact> ();
        Set<ID> setOfConIds = new Set<ID>();
        
        if(obj.mapOfContToInsert.size() > 0){
        
            for(Contact c : obj.mapOfContToInsert.values()){
                setOfConIds.add(c.ID);
            }
            
            ListOfDupCon = [select id, FLAS__c, FLAS_2__c, LAZ__c, LAZ_2__c, PL__c, PL_2__c, PF__c, PF_2__c,
                   Email, Email_2__c from contact where Id IN: setOfConIds  ];       
        }      
        return ListOfDupCon;
    }
}